version: '3.8'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.110.2.1/24
  base_net:
    driver: bridge
    name: base_net
    external: true

services:
  dash:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    restart: "always"
    networks:
       net:
         ipv4_address: 172.110.2.8
    ports:
      - "30001:18888"
      - "30002:18888"
    expose:
      - "18888"
      - "18889"
  cache:
    image: "docker.io/library/redis:7.4"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    env_file:
      - CACHE_PASSWORD.env
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
    expose:
      - "6379"
    networks:
      - "base_net"
  postgres:
    image: "docker.io/library/postgres:17.5"
    env_file:
      - POSTGRES_PASSWORD.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    ports:
      - "30010:5432"
    volumes:
      - type: "bind"
        target: "/var/lib/postgresql/data"
        source: "/home/mossimo/aigioltemplate/postgresql/data"
        read_only: false
    networks:
      - "net"
  api-bm:
    image: docker.mossimo.net:1443/aigioltemplate/aigioltemplate-api-bm:latest
    restart: always
    hostname: api-bm
    env_file:
      - POSTGRES_PASSWORD.env
      - CACHE_PASSWORD.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://dash:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_HTTP_PORT: "80"
      OTEL_SERVICE_NAME: "api-bm"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      ConnectionStrings__aigioltemplate: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=aigioltemplate"
    depends_on:
      cache:
        condition: "service_started"
      postgres:
        condition: "service_started"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
       net:
         ipv4_address: 172.110.2.3
       base_net:
    ports:
      - "30020:80"
    volumes:
      - ./appsettings/all.json:/app/appsettings.json
      - ./appsettings/all.json:/app/appsettings.Development.json
      - ./logs/bm/:/app/logs